# Generated by Django 4.1.5 on 2023-01-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gry', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokoj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=20)),
            ],
        ),
    ]
